/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.Columna;
import BackEnd.Controlador;
import BackEnd.Esquema;
import BackEnd.Tabla;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author pimie
 */
public class MainWindow extends javax.swing.JFrame {

   DefaultTableModel modelo; 
    Controlador controlador;

    public MainWindow(Controlador controlador) {

        this.controlador = controlador;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
       
        }
        
    

    MainWindow() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        boxEsquemas = new javax.swing.JComboBox<>();
        txtNombreEsquema = new javax.swing.JTextField();
        BtnNuevoEsquema = new javax.swing.JButton();
        BtnBorrarEsquema = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrincipal = new javax.swing.JTable();
        BoxColumnas = new javax.swing.JComboBox<>();
        txtDatoBuscar = new javax.swing.JTextField();
        BtnBuscarDato = new javax.swing.JButton();
        BtnBorrarDato = new javax.swing.JButton();
        BtnCargarDatos = new javax.swing.JButton();
        txtBusquedaSql = new javax.swing.JTextField();
        BtnBuscarSql = new javax.swing.JButton();
        boxTablas = new javax.swing.JComboBox<>();
        txtNombreTabla = new javax.swing.JTextField();
        BtnNuevaTabla = new javax.swing.JButton();
        BtnBorrarTabla = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiNoSQL");

        jPanel1.setBackground(new java.awt.Color(1, 22, 39));

        boxEsquemas.setBackground(new java.awt.Color(53, 60, 81));
        boxEsquemas.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        boxEsquemas.setForeground(new java.awt.Color(255, 255, 255));
        boxEsquemas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxEsquemasItemStateChanged(evt);
            }
        });
        boxEsquemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEsquemasActionPerformed(evt);
            }
        });

        txtNombreEsquema.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreEsquema.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNombreEsquema.setForeground(new java.awt.Color(1, 22, 39));
        txtNombreEsquema.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreEsquema.setText("Ingresa nombre del esquema");
        txtNombreEsquema.setToolTipText("Ingresa nombre del esquema");
        txtNombreEsquema.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreEsquema.setName(""); // NOI18N
        txtNombreEsquema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreEsquemaMouseClicked(evt);
            }
        });
        txtNombreEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEsquemaActionPerformed(evt);
            }
        });

        BtnNuevoEsquema.setBackground(new java.awt.Color(193, 240, 249));
        BtnNuevoEsquema.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnNuevoEsquema.setForeground(new java.awt.Color(1, 22, 39));
        BtnNuevoEsquema.setText("Nuevo Esquema");
        BtnNuevoEsquema.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnNuevoEsquema.setMinimumSize(new java.awt.Dimension(70, 17));
        BtnNuevoEsquema.setPreferredSize(new java.awt.Dimension(70, 17));
        BtnNuevoEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoEsquemaActionPerformed(evt);
            }
        });

        BtnBorrarEsquema.setBackground(new java.awt.Color(193, 240, 249));
        BtnBorrarEsquema.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBorrarEsquema.setForeground(new java.awt.Color(1, 22, 39));
        BtnBorrarEsquema.setText("Borrar Esquema");
        BtnBorrarEsquema.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBorrarEsquema.setMinimumSize(new java.awt.Dimension(70, 17));
        BtnBorrarEsquema.setPreferredSize(new java.awt.Dimension(70, 17));
        BtnBorrarEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarEsquemaActionPerformed(evt);
            }
        });

        jTablePrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jTablePrincipal.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jTablePrincipal.setForeground(new java.awt.Color(1, 22, 39));
        jTablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePrincipal.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTablePrincipal);
        jTablePrincipal.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        BoxColumnas.setBackground(new java.awt.Color(53, 60, 81));
        BoxColumnas.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BoxColumnas.setForeground(new java.awt.Color(255, 255, 255));
        BoxColumnas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDatoBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtDatoBuscar.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtDatoBuscar.setForeground(new java.awt.Color(1, 22, 39));
        txtDatoBuscar.setText("Ingrese Dato a Buscar");
        txtDatoBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDatoBuscarMouseClicked(evt);
            }
        });

        BtnBuscarDato.setBackground(new java.awt.Color(193, 240, 249));
        BtnBuscarDato.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBuscarDato.setForeground(new java.awt.Color(1, 22, 39));
        BtnBuscarDato.setText("Buscar");
        BtnBuscarDato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBuscarDato.setMinimumSize(new java.awt.Dimension(77, 17));
        BtnBuscarDato.setPreferredSize(new java.awt.Dimension(77, 17));

        BtnBorrarDato.setBackground(new java.awt.Color(193, 240, 249));
        BtnBorrarDato.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBorrarDato.setForeground(new java.awt.Color(1, 22, 39));
        BtnBorrarDato.setText("Borrar");
        BtnBorrarDato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBorrarDato.setMinimumSize(new java.awt.Dimension(77, 17));
        BtnBorrarDato.setPreferredSize(new java.awt.Dimension(77, 17));

        BtnCargarDatos.setBackground(new java.awt.Color(193, 240, 249));
        BtnCargarDatos.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnCargarDatos.setForeground(new java.awt.Color(1, 22, 39));
        BtnCargarDatos.setText("Cargar Datos");
        BtnCargarDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnCargarDatos.setMinimumSize(new java.awt.Dimension(77, 17));
        BtnCargarDatos.setPreferredSize(new java.awt.Dimension(77, 17));

        txtBusquedaSql.setBackground(new java.awt.Color(255, 255, 255));
        txtBusquedaSql.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtBusquedaSql.setForeground(new java.awt.Color(1, 22, 39));
        txtBusquedaSql.setText("Busqueda SQL");
        txtBusquedaSql.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBusquedaSqlMouseClicked(evt);
            }
        });

        BtnBuscarSql.setBackground(new java.awt.Color(193, 240, 249));
        BtnBuscarSql.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBuscarSql.setForeground(new java.awt.Color(1, 22, 39));
        BtnBuscarSql.setText("Buscar");
        BtnBuscarSql.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBuscarSql.setMinimumSize(new java.awt.Dimension(77, 17));
        BtnBuscarSql.setPreferredSize(new java.awt.Dimension(77, 17));

        boxTablas.setBackground(new java.awt.Color(53, 60, 81));
        boxTablas.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        boxTablas.setForeground(new java.awt.Color(255, 255, 255));
        boxTablas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxTablasItemStateChanged(evt);
            }
        });
        boxTablas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxTablasMouseClicked(evt);
            }
        });
        boxTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTablasActionPerformed(evt);
            }
        });

        txtNombreTabla.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreTabla.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNombreTabla.setForeground(new java.awt.Color(1, 22, 39));
        txtNombreTabla.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreTabla.setText("Ingresa Nombre de la Tabla");
        txtNombreTabla.setToolTipText("Ingresa Nombre de la Tabla");
        txtNombreTabla.setPreferredSize(new java.awt.Dimension(166, 23));
        txtNombreTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreTablaMouseClicked(evt);
            }
        });
        txtNombreTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTablaActionPerformed(evt);
            }
        });

        BtnNuevaTabla.setBackground(new java.awt.Color(193, 240, 249));
        BtnNuevaTabla.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnNuevaTabla.setForeground(new java.awt.Color(1, 22, 39));
        BtnNuevaTabla.setText("Nueva Tabla");
        BtnNuevaTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnNuevaTabla.setMinimumSize(new java.awt.Dimension(70, 17));
        BtnNuevaTabla.setPreferredSize(new java.awt.Dimension(70, 17));
        BtnNuevaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevaTablaActionPerformed(evt);
            }
        });

        BtnBorrarTabla.setBackground(new java.awt.Color(193, 240, 249));
        BtnBorrarTabla.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBorrarTabla.setForeground(new java.awt.Color(1, 22, 39));
        BtnBorrarTabla.setText("Borrar Tabla");
        BtnBorrarTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBorrarTabla.setMinimumSize(new java.awt.Dimension(70, 17));
        BtnBorrarTabla.setPreferredSize(new java.awt.Dimension(70, 17));
        BtnBorrarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarTablaActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBusquedaSql)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BoxColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDatoBuscar)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnBuscarSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnBuscarDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnBorrarDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxEsquemas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreEsquema)
                                    .addComponent(txtNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnNuevaTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnNuevoEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnBorrarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnBorrarEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombreTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombreEsquema)
                                .addComponent(boxEsquemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnBorrarEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNuevoEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnNuevaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBorrarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBuscarDato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoxColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDatoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnBorrarDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEsquemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreEsquemaMouseClicked
        txtNombreEsquema.setText(" ");
    }//GEN-LAST:event_txtNombreEsquemaMouseClicked

    private void txtDatoBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDatoBuscarMouseClicked
        txtDatoBuscar.setText(null);
    }//GEN-LAST:event_txtDatoBuscarMouseClicked

    private void txtBusquedaSqlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBusquedaSqlMouseClicked
        txtBusquedaSql.setText(null);
    }//GEN-LAST:event_txtBusquedaSqlMouseClicked

    private void BtnNuevoEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoEsquemaActionPerformed
        if (!" ".equals(txtNombreEsquema.getText())) {
            agregarEsquema();

        } else {
            JOptionPane.showMessageDialog(this, "Por favor digite un nombre");
        }


    }//GEN-LAST:event_BtnNuevoEsquemaActionPerformed

    private void boxEsquemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEsquemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEsquemasActionPerformed

    private void BtnBorrarEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarEsquemaActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, "Seguro desea eliminar un esquema");
        if (JOptionPane.YES_OPTION == confirmacion) {
            borrarEsquema();
            JOptionPane.showMessageDialog(this, " Se ha eliminado el esquema ");
        } else {
            JOptionPane.showMessageDialog(this, " No se ha elimnado nada ");
        }

    }//GEN-LAST:event_BtnBorrarEsquemaActionPerformed

    private void txtNombreTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreTablaMouseClicked
        txtNombreTabla.setText(" ");
    }//GEN-LAST:event_txtNombreTablaMouseClicked

    private void boxTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTablasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTablasActionPerformed

    private void txtNombreEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEsquemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEsquemaActionPerformed

    //DEBEMOS CONDICIONAR ESTE BOTON, DE TAL MANERA QUE SI EL BOX DE ESQUEMA ESTA VACIO NO PUEDE CREAR TABLAS //Listo
    // LUEGO CONDICIONAR LAS TABLAS SEGUN EL ESQUEMA SELECCIONADO //Esto no se como hacerlo????
    // DE MANERA SILIMAR LAS  COLUMNAS DE ACUERDO A LA TABLA DONDE SE CREARON

    private void BtnNuevaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevaTablaActionPerformed

        if (!txtNombreTabla.equals("") && boxEsquemas.getItemCount() != 0) {
            agregarTabla();

        } else {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un esquema primero y digite un nombre para la tabla.");
        }

        //controlador.iniciarVentanaSecundaria();
    }//GEN-LAST:event_BtnNuevaTablaActionPerformed

    private void txtNombreTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTablaActionPerformed

    private void boxTablasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxTablasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTablasMouseClicked

    private void BtnBorrarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarTablaActionPerformed
        int confirmacionTabla = JOptionPane.showConfirmDialog(this, "Seguro desea eliminar la tabla?");
        if (JOptionPane.YES_OPTION == confirmacionTabla) {
            borrarTabla();
            JOptionPane.showMessageDialog(this, " Se ha eliminado la tabla correctamente! ");
        }
    }//GEN-LAST:event_BtnBorrarTablaActionPerformed

    private void boxTablasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxTablasItemStateChanged

    }//GEN-LAST:event_boxTablasItemStateChanged

    //LLAMADA METODO POR MODIFICAR
    private void boxEsquemasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxEsquemasItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
          //  boxTablas.setModel(new DefaultComboBoxModel(controlador.getTablas(controlador.getEsquema(boxEsquemas.getSelectedIndex()))));
            //if(controlador.getEsquemas().get(boxEsquemas.getSelectedItem()).getEsquema_ID() == controlador.getTablas().getTabla_ID()) {
            //boxTablas.setSelectedItem(null);
            //boxTablas.add(this)
        }

        //}
    }//GEN-LAST:event_boxEsquemasItemStateChanged

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        agregarColumnas();

    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxColumnas;
    private javax.swing.JButton BtnBorrarDato;
    private javax.swing.JButton BtnBorrarEsquema;
    private javax.swing.JButton BtnBorrarTabla;
    private javax.swing.JButton BtnBuscarDato;
    private javax.swing.JButton BtnBuscarSql;
    private javax.swing.JButton BtnCargarDatos;
    private javax.swing.JButton BtnNuevaTabla;
    private javax.swing.JButton BtnNuevoEsquema;
    public static javax.swing.JComboBox<String> boxEsquemas;
    public static javax.swing.JComboBox<String> boxTablas;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrincipal;
    private javax.swing.JTextField txtBusquedaSql;
    private javax.swing.JTextField txtDatoBuscar;
    private javax.swing.JTextField txtNombreEsquema;
    private javax.swing.JTextField txtNombreTabla;
    // End of variables declaration//GEN-END:variables

    ArrayList<String> esquema;
    Integer contador = 1;

    //Tablas tablaX;
    int cont = 1;
    int cont2 = 0;

//    public void asignar_id() {
//
//        asignarId.put(cont, esquema.get(cont2));
//        cont++;
//        cont2++;
//        System.out.println(asignarId.size());
//    }
    public void agregarEsquema() {
        String name = txtNombreEsquema.getText();
        Esquema nuevo = new Esquema(boxEsquemas.getSelectedIndex() + 1, name);
        nuevo.setNombre(name);
        nuevo.setEsquema_ID(boxEsquemas.getSelectedIndex() + 1);
        controlador.agregarEsquema(nuevo);
        boxEsquemas.addItem(name);
        txtNombreEsquema.setText(" ");
        System.out.println(" Se ha guardado el esquema con exito ");
        System.out.println("ID: " + nuevo.getEsquema_ID() + "nombre: " + nuevo.getNombre());
        System.out.println(controlador.getEsquemas().size());
        //contador++;

//        for (int i = 0; i < controlador.getEsquemas().size(); i++) {
//            System.out.println(" NOMBRES DE ESQUEMAS CREADO " +controlador.getEsquemas().get(contador).getEsquema_ID()+ controlador.getEsquemas().get(contador).getNombre());
//
//        }
    }

    public void borrarEsquema() {
        if (boxTablas != null) {
            // FALTA AGREGAR QUE SE BORREN LAS TABLAS ASOCIADAS AL ESQUEMA 
            controlador.getEsquemas().remove(controlador.getEsquemas().size());
            boxEsquemas.removeItemAt(controlador.getEsquemas().size());

            System.out.println(controlador.getEsquemas().size() + " Tamaño del MAP ");
        } else {
            controlador.getEsquemas().remove(controlador.getEsquemas().size());
            boxEsquemas.removeItemAt(controlador.getEsquemas().size());

            System.out.println(controlador.getEsquemas().size() + " Tamaño del MAP ");
            //contador--;
        }
    }

    public void agregarTabla() {
        String nombreTabla = txtNombreTabla.getText();
        Tabla tabla = new Tabla(boxTablas.getSelectedIndex(), nombreTabla);
        tabla.setNombre(txtNombreTabla.getText());
        Esquema esquema1 = controlador.getEsquemas().get(boxEsquemas.getSelectedIndex() + 1);
        esquema1.getTablas().add(tabla);

        boxTablas.addItem(txtNombreTabla.getText());
        //NuevaTabla.jLabelNombreTabla.setText(tabla.getNombre());
        NuevaTabla.jLabelNombreTabla.setText(txtNombreTabla.getText());
        txtNombreTabla.setText("");
        System.out.println("Se agrego una tabla correctamente al ID: " + boxEsquemas.getSelectedIndex() + 1);
        System.out.println("TAMANO DEL ARRAYlIS DE TABLAS AL AGREGAR " + esquema1.getTablas().size());

    }

    public void borrarTabla() {//arreglar temprano

        if (controlador.getEsquemas().size() > 0) {

            boxTablas.remove(controlador.getEsquemas().get(boxEsquemas.getSelectedIndex()).getTablas().size());
            System.out.println("TAMANO DEL ARRAYLIST DE TABLAS DESPUES DE BORRAR = " + controlador.getEsquemas().get(boxEsquemas.getSelectedIndex() + 1).getTablas().size());
        }
    }

    public void agregarColumnas() {
        Tabla prueba = new Tabla();
        prueba.clonarColumnas();
        System.out.println(prueba.getColumnas().get(0).getNombre());
      

    }

    //REVISAR PORQUE LANZA ERROR EN LA LINEA 576
//    public void establecerColumnas(ArrayList<Columna> obtenerColumnas) {
//        DefaultTableModel dtm = new DefaultTableModel();
//        System.out.println(obtenerColumnas.size());
//        for (int i = 0; i < obtenerColumnas.size(); i++) {
//            //dtm.setColumnIdentifiers(obtenerColumnas); //Lanza ERROR
//            dtm.addColumn(obtenerColumnas); //Teoricamente funciona bien!
//        }
//        System.out.println(dtm.getColumnCount());
//        jTablePrincipal.setModel(dtm);
//    }
}
//NO TOCAR!!!
//public void crearColumnas(ArrayList<String> listaColumnas) {
//        //InterfazNuevaTabla obtenerTitulosColumnas = new NuevaTabla();
//        ArrayList<Tablas> tablas = new ArrayList<>();
//        this.tablas = tablas;
//
//        System.out.println(listaColumnas.size());
//        System.out.println(tablas.size());
//System.out.println(obtenerTitulosColumnas.titulosColumnas.size());
//int varTablas = tablas.indexOf(tablas.get(contadorTablas));
//tablas.get(contadorTablas).setNumColumnas(listaColumnas.size());
//System.out.println(tablas.get(contadorTablas).getNumColumnas());
/*
        for (int i = 0; i < tablas.get(contadorTablas).getNumColumnas(); i++) {
            TableColumn tc = new TableColumn(i + 1, 80);
            jTablePrincipal.addColumn(tc);
        }
 */
//        contadorTablas++;
//}

//}
