/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.Columna;
import BackEnd.Controlador;
import BackEnd.Esquema;
import BackEnd.Tabla;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.DefaultComboBoxModel;
import java.awt.Color;
import static javafx.beans.binding.Bindings.select;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author pimie
 */
public class MainWindow extends javax.swing.JFrame {

    public ArrayList<Columna> titulosColumnas = new ArrayList<>();

    DefaultTableModel modelo;
    Controlador controlador;

    public MainWindow(Controlador controlador) {

        this.controlador = controlador;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    MainWindow() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Base = new javax.swing.JPanel();
        jPanel1_Principal = new javax.swing.JPanel();
        boxEsquemas = new javax.swing.JComboBox<>();
        txtNombreEsquema = new javax.swing.JTextField();
        BtnNuevoEsquema = new javax.swing.JButton();
        BtnBorrarEsquema = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrincipal = new javax.swing.JTable();
        BoxColumnas = new javax.swing.JComboBox<>();
        txtDatoBuscar = new javax.swing.JTextField();
        BtnBuscarDato = new javax.swing.JButton();
        BtnBorrarDato = new javax.swing.JButton();
        txtBusquedaSql = new javax.swing.JTextField();
        BtnBuscarSql = new javax.swing.JButton();
        boxTablas = new javax.swing.JComboBox<>();
        txtNombreTabla = new javax.swing.JTextField();
        BtnNuevaTabla = new javax.swing.JButton();
        BtnBorrarTabla = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2_SlideBase = new javax.swing.JPanel();
        jPanel3_SlideColumnas = new javax.swing.JPanel();
        txtNombreColumna = new javax.swing.JTextField();
        btnListo = new javax.swing.JButton();
        btnNuevaColumna = new javax.swing.JButton();
        jPanel4_MostrarColumnas = new javax.swing.JPanel();
        JLabelColum1 = new javax.swing.JLabel();
        JLabelColum2 = new javax.swing.JLabel();
        JLabelColum3 = new javax.swing.JLabel();
        JLabelColum4 = new javax.swing.JLabel();
        JLabelColum5 = new javax.swing.JLabel();
        btnBorrar1 = new javax.swing.JButton();
        btnBorrar2 = new javax.swing.JButton();
        btnBorrar3 = new javax.swing.JButton();
        btnBorrar4 = new javax.swing.JButton();
        btnBorrar5 = new javax.swing.JButton();
        jLabelNombreTabla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiNoSQL");

        jPanel_Base.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1_Principal.setBackground(new java.awt.Color(255, 255, 255));

        boxEsquemas.setBackground(new java.awt.Color(53, 60, 81));
        boxEsquemas.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        boxEsquemas.setForeground(new java.awt.Color(255, 255, 255));
        boxEsquemas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxEsquemasItemStateChanged(evt);
            }
        });
        boxEsquemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEsquemasActionPerformed(evt);
            }
        });

        txtNombreEsquema.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreEsquema.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNombreEsquema.setForeground(new java.awt.Color(1, 22, 39));
        txtNombreEsquema.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreEsquema.setText("Ingresa nombre del esquema");
        txtNombreEsquema.setToolTipText("Ingresa nombre del esquema");
        txtNombreEsquema.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreEsquema.setName(""); // NOI18N
        txtNombreEsquema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreEsquemaMouseClicked(evt);
            }
        });
        txtNombreEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEsquemaActionPerformed(evt);
            }
        });

        BtnNuevoEsquema.setBackground(new java.awt.Color(193, 240, 249));
        BtnNuevoEsquema.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnNuevoEsquema.setForeground(new java.awt.Color(1, 22, 39));
        BtnNuevoEsquema.setText("Nuevo Esquema");
        BtnNuevoEsquema.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnNuevoEsquema.setMinimumSize(new java.awt.Dimension(70, 17));
        BtnNuevoEsquema.setPreferredSize(new java.awt.Dimension(70, 17));
        BtnNuevoEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoEsquemaActionPerformed(evt);
            }
        });

        BtnBorrarEsquema.setBackground(new java.awt.Color(193, 240, 249));
        BtnBorrarEsquema.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBorrarEsquema.setForeground(new java.awt.Color(1, 22, 39));
        BtnBorrarEsquema.setText("Borrar Esquema");
        BtnBorrarEsquema.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBorrarEsquema.setMinimumSize(new java.awt.Dimension(70, 17));
        BtnBorrarEsquema.setPreferredSize(new java.awt.Dimension(70, 17));
        BtnBorrarEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarEsquemaActionPerformed(evt);
            }
        });

        jTablePrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jTablePrincipal.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jTablePrincipal.setForeground(new java.awt.Color(1, 22, 39));
        jTablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePrincipal.setColumnSelectionAllowed(true);
        jTablePrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePrincipal);
        jTablePrincipal.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        BoxColumnas.setBackground(new java.awt.Color(53, 60, 81));
        BoxColumnas.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BoxColumnas.setForeground(new java.awt.Color(255, 255, 255));

        txtDatoBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtDatoBuscar.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtDatoBuscar.setForeground(new java.awt.Color(1, 22, 39));
        txtDatoBuscar.setText("Ingrese Dato a Buscar");
        txtDatoBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDatoBuscarMouseClicked(evt);
            }
        });

        BtnBuscarDato.setBackground(new java.awt.Color(193, 240, 249));
        BtnBuscarDato.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBuscarDato.setForeground(new java.awt.Color(1, 22, 39));
        BtnBuscarDato.setText("Buscar");
        BtnBuscarDato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBuscarDato.setMinimumSize(new java.awt.Dimension(77, 17));
        BtnBuscarDato.setPreferredSize(new java.awt.Dimension(77, 17));

        BtnBorrarDato.setBackground(new java.awt.Color(193, 240, 249));
        BtnBorrarDato.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBorrarDato.setForeground(new java.awt.Color(1, 22, 39));
        BtnBorrarDato.setText("Borrar");
        BtnBorrarDato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBorrarDato.setMinimumSize(new java.awt.Dimension(77, 17));
        BtnBorrarDato.setPreferredSize(new java.awt.Dimension(77, 17));

        txtBusquedaSql.setBackground(new java.awt.Color(255, 255, 255));
        txtBusquedaSql.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtBusquedaSql.setForeground(new java.awt.Color(1, 22, 39));
        txtBusquedaSql.setText("Busqueda en mantenimiento.");
        txtBusquedaSql.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBusquedaSqlMouseClicked(evt);
            }
        });

        BtnBuscarSql.setBackground(new java.awt.Color(193, 240, 249));
        BtnBuscarSql.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBuscarSql.setForeground(new java.awt.Color(1, 22, 39));
        BtnBuscarSql.setText("Buscar");
        BtnBuscarSql.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBuscarSql.setMinimumSize(new java.awt.Dimension(77, 17));
        BtnBuscarSql.setPreferredSize(new java.awt.Dimension(77, 17));

        boxTablas.setBackground(new java.awt.Color(53, 60, 81));
        boxTablas.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        boxTablas.setForeground(new java.awt.Color(255, 255, 255));
        boxTablas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxTablasItemStateChanged(evt);
            }
        });
        boxTablas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxTablasMouseClicked(evt);
            }
        });
        boxTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTablasActionPerformed(evt);
            }
        });

        txtNombreTabla.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreTabla.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNombreTabla.setForeground(new java.awt.Color(1, 22, 39));
        txtNombreTabla.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreTabla.setText("Ingresa Nombre de la Tabla");
        txtNombreTabla.setToolTipText("Ingresa Nombre de la Tabla");
        txtNombreTabla.setPreferredSize(new java.awt.Dimension(166, 23));
        txtNombreTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreTablaMouseClicked(evt);
            }
        });
        txtNombreTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTablaActionPerformed(evt);
            }
        });

        BtnNuevaTabla.setBackground(new java.awt.Color(193, 240, 249));
        BtnNuevaTabla.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnNuevaTabla.setForeground(new java.awt.Color(1, 22, 39));
        BtnNuevaTabla.setText("Nueva Tabla");
        BtnNuevaTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnNuevaTabla.setMinimumSize(new java.awt.Dimension(70, 17));
        BtnNuevaTabla.setPreferredSize(new java.awt.Dimension(70, 17));
        BtnNuevaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevaTablaActionPerformed(evt);
            }
        });

        BtnBorrarTabla.setBackground(new java.awt.Color(193, 240, 249));
        BtnBorrarTabla.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBorrarTabla.setForeground(new java.awt.Color(1, 22, 39));
        BtnBorrarTabla.setText("Borrar Tabla");
        BtnBorrarTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBorrarTabla.setMinimumSize(new java.awt.Dimension(70, 17));
        BtnBorrarTabla.setPreferredSize(new java.awt.Dimension(70, 17));
        BtnBorrarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarTablaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("+");
        jButton1.setToolTipText("Agregar Fila ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setText("-");
        jButton2.setToolTipText("Agregar Fila ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_PrincipalLayout = new javax.swing.GroupLayout(jPanel1_Principal);
        jPanel1_Principal.setLayout(jPanel1_PrincipalLayout);
        jPanel1_PrincipalLayout.setHorizontalGroup(
            jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                        .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBusquedaSql)
                            .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                                .addComponent(BoxColumnas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDatoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                                .addComponent(BtnBuscarDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnBorrarDato, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnBuscarSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101))
                    .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                        .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                                .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxEsquemas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreEsquema)
                                    .addComponent(txtNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnNuevaTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnNuevoEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnBorrarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnBorrarEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel1_PrincipalLayout.setVerticalGroup(
            jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_PrincipalLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombreTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_PrincipalLayout.createSequentialGroup()
                            .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombreEsquema)
                                .addComponent(boxEsquemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)))
                    .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                        .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnBorrarEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnNuevoEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnNuevaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBorrarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                        .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BoxColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBusquedaSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1_PrincipalLayout.createSequentialGroup()
                        .addGroup(jPanel1_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnBuscarDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBorrarDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBuscarSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel_Base.add(jPanel1_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jPanel3_SlideColumnas.setBackground(new java.awt.Color(14, 34, 50));
        jPanel3_SlideColumnas.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3_SlideColumnas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreColumna.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreColumna.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNombreColumna.setForeground(new java.awt.Color(1, 22, 39));
        txtNombreColumna.setText("Nombre Columna");
        txtNombreColumna.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreColumnaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreColumnaFocusLost(evt);
            }
        });
        txtNombreColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreColumnaActionPerformed(evt);
            }
        });
        jPanel3_SlideColumnas.add(txtNombreColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 128, 30));

        btnListo.setBackground(new java.awt.Color(193, 240, 249));
        btnListo.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnListo.setForeground(new java.awt.Color(1, 22, 39));
        btnListo.setText("Listo");
        btnListo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        btnListo.setPreferredSize(new java.awt.Dimension(40, 30));
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        jPanel3_SlideColumnas.add(btnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 80, -1));

        btnNuevaColumna.setBackground(new java.awt.Color(193, 240, 249));
        btnNuevaColumna.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnNuevaColumna.setForeground(new java.awt.Color(1, 22, 39));
        btnNuevaColumna.setText("Nueva Columna");
        btnNuevaColumna.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        btnNuevaColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaColumnaActionPerformed(evt);
            }
        });
        jPanel3_SlideColumnas.add(btnNuevaColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, 30));

        jPanel4_MostrarColumnas.setBackground(new java.awt.Color(1, 22, 39));

        JLabelColum1.setBackground(new java.awt.Color(255, 255, 255));
        JLabelColum1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        JLabelColum1.setForeground(new java.awt.Color(255, 255, 255));
        JLabelColum1.setToolTipText("Nombre Columna 1");

        JLabelColum2.setBackground(new java.awt.Color(255, 255, 255));
        JLabelColum2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        JLabelColum2.setForeground(new java.awt.Color(255, 255, 255));
        JLabelColum2.setToolTipText("Nombre Columna 1");

        JLabelColum3.setBackground(new java.awt.Color(255, 255, 255));
        JLabelColum3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        JLabelColum3.setForeground(new java.awt.Color(255, 255, 255));
        JLabelColum3.setToolTipText("Nombre Columna 1");

        JLabelColum4.setBackground(new java.awt.Color(255, 255, 255));
        JLabelColum4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        JLabelColum4.setForeground(new java.awt.Color(255, 255, 255));
        JLabelColum4.setToolTipText("Nombre Columna 1");

        JLabelColum5.setBackground(new java.awt.Color(255, 255, 255));
        JLabelColum5.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        JLabelColum5.setForeground(new java.awt.Color(255, 255, 255));
        JLabelColum5.setToolTipText("Nombre Columna 1");

        javax.swing.GroupLayout jPanel4_MostrarColumnasLayout = new javax.swing.GroupLayout(jPanel4_MostrarColumnas);
        jPanel4_MostrarColumnas.setLayout(jPanel4_MostrarColumnasLayout);
        jPanel4_MostrarColumnasLayout.setHorizontalGroup(
            jPanel4_MostrarColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_MostrarColumnasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4_MostrarColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelColum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelColum2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(JLabelColum5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(JLabelColum4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabelColum3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4_MostrarColumnasLayout.setVerticalGroup(
            jPanel4_MostrarColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_MostrarColumnasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JLabelColum1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelColum2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelColum3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLabelColum4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(JLabelColum5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3_SlideColumnas.add(jPanel4_MostrarColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 210));

        btnBorrar1.setBackground(new java.awt.Color(193, 240, 249));
        btnBorrar1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnBorrar1.setForeground(new java.awt.Color(1, 22, 39));
        btnBorrar1.setText("X");
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });
        jPanel3_SlideColumnas.add(btnBorrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        btnBorrar2.setBackground(new java.awt.Color(193, 240, 249));
        btnBorrar2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnBorrar2.setForeground(new java.awt.Color(1, 22, 39));
        btnBorrar2.setText("X");
        btnBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar2ActionPerformed(evt);
            }
        });
        jPanel3_SlideColumnas.add(btnBorrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        btnBorrar3.setBackground(new java.awt.Color(193, 240, 249));
        btnBorrar3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnBorrar3.setForeground(new java.awt.Color(1, 22, 39));
        btnBorrar3.setText("X");
        btnBorrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar3ActionPerformed(evt);
            }
        });
        jPanel3_SlideColumnas.add(btnBorrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        btnBorrar4.setBackground(new java.awt.Color(193, 240, 249));
        btnBorrar4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnBorrar4.setForeground(new java.awt.Color(1, 22, 39));
        btnBorrar4.setText("X");
        btnBorrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar4ActionPerformed(evt);
            }
        });
        jPanel3_SlideColumnas.add(btnBorrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        btnBorrar5.setBackground(new java.awt.Color(193, 240, 249));
        btnBorrar5.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnBorrar5.setForeground(new java.awt.Color(1, 22, 39));
        btnBorrar5.setText("X");
        btnBorrar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar5ActionPerformed(evt);
            }
        });
        jPanel3_SlideColumnas.add(btnBorrar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 30));

        jLabelNombreTabla.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelNombreTabla.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3_SlideColumnas.add(jLabelNombreTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 130, 30));

        javax.swing.GroupLayout jPanel2_SlideBaseLayout = new javax.swing.GroupLayout(jPanel2_SlideBase);
        jPanel2_SlideBase.setLayout(jPanel2_SlideBaseLayout);
        jPanel2_SlideBaseLayout.setHorizontalGroup(
            jPanel2_SlideBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_SlideBaseLayout.createSequentialGroup()
                .addComponent(jPanel3_SlideColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel2_SlideBaseLayout.setVerticalGroup(
            jPanel2_SlideBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3_SlideColumnas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel_Base.add(jPanel2_SlideBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 210, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Base, javax.swing.GroupLayout.PREFERRED_SIZE, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEsquemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreEsquemaMouseClicked
        txtNombreEsquema.setText(" ");
    }//GEN-LAST:event_txtNombreEsquemaMouseClicked

    private void txtDatoBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDatoBuscarMouseClicked
        txtDatoBuscar.setText(null);
    }//GEN-LAST:event_txtDatoBuscarMouseClicked

    private void txtBusquedaSqlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBusquedaSqlMouseClicked
        txtBusquedaSql.setText(null);
    }//GEN-LAST:event_txtBusquedaSqlMouseClicked

    private void BtnNuevoEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoEsquemaActionPerformed
        if (!" ".equals(txtNombreEsquema.getText())) {
            agregarEsquema();

        } else {
            JOptionPane.showMessageDialog(this, "Por favor digite un nombre");
        }


    }//GEN-LAST:event_BtnNuevoEsquemaActionPerformed

    private void boxEsquemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEsquemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEsquemasActionPerformed

    private void BtnBorrarEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarEsquemaActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, "Seguro desea eliminar un esquema");
        if (JOptionPane.YES_OPTION == confirmacion) {
            borrarEsquema();
            JOptionPane.showMessageDialog(this, " Se ha eliminado el esquema ");
        } else {
            JOptionPane.showMessageDialog(this, " No se ha elimnado nada ");
        }

    }//GEN-LAST:event_BtnBorrarEsquemaActionPerformed

    private void txtNombreTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreTablaMouseClicked
        txtNombreTabla.setText(" ");
    }//GEN-LAST:event_txtNombreTablaMouseClicked

    private void boxTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTablasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTablasActionPerformed

    private void txtNombreEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEsquemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEsquemaActionPerformed

    //DEBEMOS CONDICIONAR ESTE BOTON, DE TAL MANERA QUE SI EL BOX DE ESQUEMA ESTA VACIO NO PUEDE CREAR TABLAS //Listo
    // LUEGO CONDICIONAR LAS TABLAS SEGUN EL ESQUEMA SELECCIONADO //Esto no se como hacerlo????
    // DE MANERA SILIMAR LAS  COLUMNAS DE ACUERDO A LA TABLA DONDE SE CREARON

    private void BtnNuevaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevaTablaActionPerformed

        if (!txtNombreTabla.equals("") && boxEsquemas.getItemCount() != 0) {
            agregarTabla();

        } else {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un esquema primero y digite un nombre para la tabla.");
        }

        jPanel2_SlideBase.setVisible(true);
    }//GEN-LAST:event_BtnNuevaTablaActionPerformed

    private void txtNombreTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTablaActionPerformed

    private void boxTablasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxTablasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTablasMouseClicked

    private void BtnBorrarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarTablaActionPerformed
        int confirmacionTabla = JOptionPane.showConfirmDialog(this, "Seguro desea eliminar la tabla?");
        if (JOptionPane.YES_OPTION == confirmacionTabla) {
            borrarTabla();
            JOptionPane.showMessageDialog(this, " Se ha eliminado la tabla correctamente! ");
        }
    }//GEN-LAST:event_BtnBorrarTablaActionPerformed

    private void boxTablasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxTablasItemStateChanged
        jLabelNombreTabla.setText((String) boxTablas.getSelectedItem());
    }//GEN-LAST:event_boxTablasItemStateChanged


    private void boxEsquemasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxEsquemasItemStateChanged
        //Esquema esquema1;
        //esquema1 = controlador.getEsquemas().get(boxEsquemas.getSelectedIndex());
        if(evt.getStateChange()== ItemEvent.SELECTED) {
             String item = (String) evt.getItem();
            JOptionPane.showMessageDialog(this, item);
            JOptionPane.showMessageDialog(this, "HAY QUE ARREGLAAAAARLO!!!");
            
            
        }
        
//        
////        for (int i = 0; i < esquema1.getTablas().size(); i++) {
////       esquema1.getTablas().get(i).getNombre();
//    if( boxTablas.getSize()==null){
//        System.out.println("Agrega tabla");
//    }else{
//        for (Tabla tablas : esquema1.getTablas()) {
//            modelo.addColumn(tablas);
//            BoxColumnas.addItem(tablas.getNombre());
//        }
//    }

    }//GEN-LAST:event_boxEsquemasItemStateChanged

    private void txtNombreColumnaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreColumnaFocusGained

        if (txtNombreColumna.getText().equals("Nombre Columna")) {
            txtNombreColumna.setText("");
            txtNombreColumna.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtNombreColumnaFocusGained

    private void txtNombreColumnaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreColumnaFocusLost

        if (txtNombreColumna.getText().equals("")) {
            txtNombreColumna.setText("Nombre Columna");
            txtNombreColumna.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtNombreColumnaFocusLost

    private void txtNombreColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreColumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreColumnaActionPerformed

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed

        modelo = new DefaultTableModel();
        for (Columna cadena : titulosColumnas) {
            modelo.addColumn(cadena);
            BoxColumnas.addItem(cadena.getNombre());
        }
        this.jTablePrincipal.setModel(modelo);
        JLabelColum1.setText(" ");
        JLabelColum2.setText(" ");
        JLabelColum3.setText(" ");
        JLabelColum4.setText(" ");
        JLabelColum5.setText(" ");
        contadorColumnas = 0;
        jPanel2_SlideBase.setVisible(false);
    }//GEN-LAST:event_btnListoActionPerformed

    private void btnNuevaColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaColumnaActionPerformed

        String nombreColumna = txtNombreColumna.getText();
        int idColumna = boxEsquemas.getSelectedIndex();
        Columna columna = new Columna(nombreColumna, idColumna);
        //   System.out.println(controlador.getEsquemas().get(MainWindow.boxEsquemas.getSelectedIndex()).getTablas().get(MainWindow.boxTablas.getSelectedIndex()).getColumnas().size());
        titulosColumnas.add(columna);
        txtNombreColumna.setText("");
        System.out.println("**Se agrego una columna**");

        switch (contadorColumnas) {
            case 0:
                JLabelColum1.setText(titulosColumnas.get(contadorColumnas).getNombre());
                JLabelColum1.setEnabled(true);
                btnBorrar1.setEnabled(true);
                break;

            case 1:
                JLabelColum2.setText(titulosColumnas.get(contadorColumnas).getNombre());
                JLabelColum2.setEnabled(true);
                btnBorrar2.setEnabled(true);
                break;

            case 2:
                JLabelColum3.setText(titulosColumnas.get(contadorColumnas).getNombre());
                JLabelColum3.setEnabled(true);
                btnBorrar3.setEnabled(true);
                break;
            case 3:
                JLabelColum4.setText(titulosColumnas.get(contadorColumnas).getNombre());
                JLabelColum4.setEnabled(true);
                btnBorrar4.setEnabled(true);
                break;
            case 4:
                JLabelColum5.setText(titulosColumnas.get(contadorColumnas).getNombre());
                JLabelColum5.setEnabled(true);
                btnBorrar5.setEnabled(true);
                break;
        }

        for (int i = 0; i < titulosColumnas.size(); i++) {
            System.out.println(titulosColumnas.get(i));
        }

        System.out.println(titulosColumnas.size());
        contadorColumnas++;
    }//GEN-LAST:event_btnNuevaColumnaActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        JLabelColum1.setText(null);
        btnBorrar1.setEnabled(false);
        titulosColumnas.remove(0);
        contadorColumnas--;
        System.out.println("Se elimino una columnas");
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar2ActionPerformed
        JLabelColum2.setText(null);
        btnBorrar2.setEnabled(false);
        titulosColumnas.remove(1);
        contadorColumnas--;
        System.out.println("Se elimino una columnas");
    }//GEN-LAST:event_btnBorrar2ActionPerformed

    private void btnBorrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar3ActionPerformed
        JLabelColum3.setText(null);
        btnBorrar3.setEnabled(false);
        titulosColumnas.remove(2);
        contadorColumnas--;
        System.out.println("Se elimino una columnas");
    }//GEN-LAST:event_btnBorrar3ActionPerformed

    private void btnBorrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar4ActionPerformed
        JLabelColum4.setText(null);
        btnBorrar4.setEnabled(false);
        titulosColumnas.remove(3);
        contadorColumnas--;
        System.out.println("Se elimino una columnas");
    }//GEN-LAST:event_btnBorrar4ActionPerformed

    private void btnBorrar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar5ActionPerformed
        JLabelColum5.setText(null);
        btnBorrar5.setEnabled(false);
        titulosColumnas.remove(4);
        contadorColumnas--;
        System.out.println("Se elimino una columnas");
    }//GEN-LAST:event_btnBorrar5ActionPerformed

    private void jTablePrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePrincipalMouseClicked

    }//GEN-LAST:event_jTablePrincipalMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTablePrincipal.getSize() != null) {
            modelo.addRow(new Object[]{" "});
        }else{
            JOptionPane.showMessageDialog(this, "Agregue una tabla por favor!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modelo.removeRow(modelo.getRowCount() - 1);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxColumnas;
    private javax.swing.JButton BtnBorrarDato;
    private javax.swing.JButton BtnBorrarEsquema;
    private javax.swing.JButton BtnBorrarTabla;
    private javax.swing.JButton BtnBuscarDato;
    private javax.swing.JButton BtnBuscarSql;
    private javax.swing.JButton BtnNuevaTabla;
    private javax.swing.JButton BtnNuevoEsquema;
    private javax.swing.JLabel JLabelColum1;
    private javax.swing.JLabel JLabelColum2;
    private javax.swing.JLabel JLabelColum3;
    private javax.swing.JLabel JLabelColum4;
    private javax.swing.JLabel JLabelColum5;
    public static javax.swing.JComboBox<String> boxEsquemas;
    public static javax.swing.JComboBox<String> boxTablas;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnBorrar2;
    private javax.swing.JButton btnBorrar3;
    private javax.swing.JButton btnBorrar4;
    private javax.swing.JButton btnBorrar5;
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnNuevaColumna;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JLabel jLabelNombreTabla;
    public static javax.swing.JPanel jPanel1_Principal;
    public static javax.swing.JPanel jPanel2_SlideBase;
    public static javax.swing.JPanel jPanel3_SlideColumnas;
    private javax.swing.JPanel jPanel4_MostrarColumnas;
    private javax.swing.JPanel jPanel_Base;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrincipal;
    private javax.swing.JTextField txtBusquedaSql;
    private javax.swing.JTextField txtDatoBuscar;
    private javax.swing.JTextField txtNombreColumna;
    private javax.swing.JTextField txtNombreEsquema;
    private javax.swing.JTextField txtNombreTabla;
    // End of variables declaration//GEN-END:variables

    ArrayList<String> esquema;
    Integer contador = 1;
    int contadorColumnas = 0;

    //Tablas tablaX;
    int cont = 1;
    int cont2 = 0;

//    public void asignar_id() {
//
//        asignarId.put(cont, esquema.get(cont2));
//        cont++;
//        cont2++;
//        System.out.println(asignarId.size());
//    }
    public void agregarEsquema() {
        String name = txtNombreEsquema.getText();
        Esquema nuevo = new Esquema(boxEsquemas.getSelectedIndex() + 1, name);
        nuevo.setNombre(name);
        nuevo.setEsquema_ID(boxEsquemas.getSelectedIndex() + 1);
        controlador.agregarEsquema(nuevo);
        boxEsquemas.addItem(name);
        txtNombreEsquema.setText(" ");
        System.out.println(" Se ha guardado el esquema con exito ");
        System.out.println("ID: " + nuevo.getEsquema_ID() + " nombre: " + nuevo.getNombre());
        System.out.println(controlador.getEsquemas().size());
        //contador++;

//        for (int i = 0; i < controlador.getEsquemas().size(); i++) {
//            System.out.println(" NOMBRES DE ESQUEMAS CREADO " +controlador.getEsquemas().get(contador).getEsquema_ID()+ controlador.getEsquemas().get(contador).getNombre());
//
//        }
    }

    public void borrarEsquema() {
        if (boxTablas != null) {
            // FALTA AGREGAR QUE SE BORREN LAS TABLAS ASOCIADAS AL ESQUEMA 
            controlador.getEsquemas().remove(controlador.getEsquemas().size());
            boxEsquemas.removeItemAt(controlador.getEsquemas().size());

            System.out.println(controlador.getEsquemas().size() + " Tamaño del MAP ");
        } else {
            controlador.getEsquemas().remove(controlador.getEsquemas().size());
            boxEsquemas.removeItemAt(controlador.getEsquemas().size());

            System.out.println(controlador.getEsquemas().size() + " Tamaño del MAP ");
            //contador--;
        }
    }

    public void agregarTabla() {
        String nombreTabla = txtNombreTabla.getText();
        Tabla tabla = new Tabla(boxEsquemas.getSelectedIndex(), nombreTabla);
        tabla.setNombre(txtNombreTabla.getText());
        Esquema esquema1 = controlador.getEsquemas().get(boxEsquemas.getSelectedIndex() + 1);
        esquema1.getTablas().add(tabla);

        boxTablas.addItem(txtNombreTabla.getText());
        //NuevaTabla.jLabelNombreTabla.setText(tabla.getNombre());
        //NuevaTabla.jLabelNombreTabla.setText(txtNombreTabla.getText());
        txtNombreTabla.setText("");
        System.out.println("Se agrego una tabla correctamente al ID: " + boxEsquemas.getSelectedIndex() + 1);
        System.out.println("TAMANO DEL ARRAYlIS DE TABLAS AL AGREGAR " + esquema1.getTablas().size());
        System.out.println(esquema1.getTablas().get(0).getTabla_ID());
        for (int i = 0; i < esquema1.getTablas().size(); i++) {
            System.out.println(esquema1.getTablas().get(i).getNombre());
        }

    }

    public void borrarTabla() {//arreglar temprano

        if (controlador.getEsquemas().size() > 0) {

            boxTablas.remove(controlador.getEsquemas().get(boxEsquemas.getSelectedIndex()).getTablas().size());
            System.out.println("TAMANO DEL ARRAYLIST DE TABLAS DESPUES DE BORRAR = " + controlador.getEsquemas().get(boxEsquemas.getSelectedIndex() + 1).getTablas().size());
        }
    }

    public void agregarColumnas() {
        Tabla prueba = new Tabla();
        prueba.clonarColumnas();
        System.out.println(prueba.getColumnas().get(0).getNombre());

    }

    public void setiarboxTablas() {
        ArrayList<Esquema> seleccion = new ArrayList<Esquema>();
        {

        }

    }

    //REVISAR PORQUE LANZA ERROR EN LA LINEA 576
//    public void establecerColumnas(ArrayList<Columna> obtenerColumnas) {
//        DefaultTableModel dtm = new DefaultTableModel();
//        System.out.println(obtenerColumnas.size());
//        for (int i = 0; i < obtenerColumnas.size(); i++) {
//            //dtm.setColumnIdentifiers(obtenerColumnas); //Lanza ERROR
//            dtm.addColumn(obtenerColumnas); //Teoricamente funciona bien!
//        }
//        System.out.println(dtm.getColumnCount());
//        jTablePrincipal.setModel(dtm);
//    }
}
//NO TOCAR!!!
//public void crearColumnas(ArrayList<String> listaColumnas) {
//        //InterfazNuevaTabla obtenerTitulosColumnas = new NuevaTabla();
//        ArrayList<Tablas> tablas = new ArrayList<>();
//        this.tablas = tablas;
//
//        System.out.println(listaColumnas.size());
//        System.out.println(tablas.size());
//System.out.println(obtenerTitulosColumnas.titulosColumnas.size());
//int varTablas = tablas.indexOf(tablas.get(contadorTablas));
//tablas.get(contadorTablas).setNumColumnas(listaColumnas.size());
//System.out.println(tablas.get(contadorTablas).getNumColumnas());
/*
        for (int i = 0; i < tablas.get(contadorTablas).getNumColumnas(); i++) {
            TableColumn tc = new TableColumn(i + 1, 80);
            jTablePrincipal.addColumn(tc);
        }
 */
//        contadorTablas++;
//}

//}
