/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Back.Controlador;
import Back.Esquema;
import Back.Tabla;
import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author pimie
 */
public class Interfaz extends javax.swing.JFrame {

    /* **FABIAN IMPORTANTE** al realizar esta instancia he intentar vincular 
    la interfaz secundaria a esta principal me lanza el error: java.lang.StackOverflowError */ //OTRA VEZ...! :(
    //InterfazNuevaTabla creacionJTable = new InterfazNuevaTabla(); // DESCOMENTAR ESTA LINEA Y PROBAR
    //NOTA ADICIONAL: Revisar linea 341 
    Controlador controlador;

    public Interfaz(Controlador controlador) {
        this.controlador = controlador;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    private Interfaz() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boxEsquemas = new javax.swing.JComboBox<>();
        txtNombreEsquema = new javax.swing.JTextField();
        BtnNuevoEsquema = new javax.swing.JButton();
        BtnBorrarEsquema = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrincipal = new javax.swing.JTable();
        BoxColumnas = new javax.swing.JComboBox<>();
        txtDatoBuscar = new javax.swing.JTextField();
        BtnBuscarDato = new javax.swing.JButton();
        BtnBorrarDato = new javax.swing.JButton();
        BtnCargarDatos = new javax.swing.JButton();
        txtBusquedaSql = new javax.swing.JTextField();
        BtnBuscarSql = new javax.swing.JButton();
        boxTablas = new javax.swing.JComboBox<>();
        txtNombreTabla = new javax.swing.JTextField();
        BtnNuevaTabla = new javax.swing.JButton();
        BtnBorrarTabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiNoSQL");

        jPanel1.setBackground(new java.awt.Color(1, 22, 39));

        boxEsquemas.setBackground(new java.awt.Color(53, 60, 81));
        boxEsquemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEsquemasActionPerformed(evt);
            }
        });

        txtNombreEsquema.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreEsquema.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNombreEsquema.setForeground(new java.awt.Color(1, 22, 39));
        txtNombreEsquema.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreEsquema.setText("Ingresa nombre del esquema");
        txtNombreEsquema.setToolTipText("Ingresa nombre del esquema");
        txtNombreEsquema.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreEsquema.setName(""); // NOI18N
        txtNombreEsquema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreEsquemaMouseClicked(evt);
            }
        });
        txtNombreEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEsquemaActionPerformed(evt);
            }
        });

        BtnNuevoEsquema.setBackground(new java.awt.Color(193, 240, 249));
        BtnNuevoEsquema.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnNuevoEsquema.setForeground(new java.awt.Color(1, 22, 39));
        BtnNuevoEsquema.setText("Nuevo Esquema");
        BtnNuevoEsquema.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnNuevoEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoEsquemaActionPerformed(evt);
            }
        });

        BtnBorrarEsquema.setBackground(new java.awt.Color(193, 240, 249));
        BtnBorrarEsquema.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBorrarEsquema.setForeground(new java.awt.Color(1, 22, 39));
        BtnBorrarEsquema.setText("Borrar Esquema");
        BtnBorrarEsquema.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBorrarEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarEsquemaActionPerformed(evt);
            }
        });

        jTablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePrincipal.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTablePrincipal);
        jTablePrincipal.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        BoxColumnas.setBackground(new java.awt.Color(53, 60, 81));
        BoxColumnas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDatoBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtDatoBuscar.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtDatoBuscar.setForeground(new java.awt.Color(1, 22, 39));
        txtDatoBuscar.setText("Ingrese Dato a Buscar");
        txtDatoBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDatoBuscarMouseClicked(evt);
            }
        });

        BtnBuscarDato.setBackground(new java.awt.Color(193, 240, 249));
        BtnBuscarDato.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBuscarDato.setForeground(new java.awt.Color(1, 22, 39));
        BtnBuscarDato.setText("Buscar");
        BtnBuscarDato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N

        BtnBorrarDato.setBackground(new java.awt.Color(193, 240, 249));
        BtnBorrarDato.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBorrarDato.setForeground(new java.awt.Color(1, 22, 39));
        BtnBorrarDato.setText("Borrar");
        BtnBorrarDato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N

        BtnCargarDatos.setBackground(new java.awt.Color(193, 240, 249));
        BtnCargarDatos.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnCargarDatos.setForeground(new java.awt.Color(1, 22, 39));
        BtnCargarDatos.setText("Cargar Datos");
        BtnCargarDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N

        txtBusquedaSql.setBackground(new java.awt.Color(255, 255, 255));
        txtBusquedaSql.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtBusquedaSql.setForeground(new java.awt.Color(1, 22, 39));
        txtBusquedaSql.setText("Busqueda SQL");
        txtBusquedaSql.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBusquedaSqlMouseClicked(evt);
            }
        });

        BtnBuscarSql.setBackground(new java.awt.Color(193, 240, 249));
        BtnBuscarSql.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBuscarSql.setForeground(new java.awt.Color(1, 22, 39));
        BtnBuscarSql.setText("Buscar");
        BtnBuscarSql.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N

        boxTablas.setBackground(new java.awt.Color(53, 60, 81));
        boxTablas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxTablasMouseClicked(evt);
            }
        });
        boxTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTablasActionPerformed(evt);
            }
        });

        txtNombreTabla.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreTabla.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNombreTabla.setForeground(new java.awt.Color(1, 22, 39));
        txtNombreTabla.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreTabla.setText("Ingresa Nombre de la Tabla");
        txtNombreTabla.setToolTipText("Ingresa Nombre de la Tabla");
        txtNombreTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreTablaMouseClicked(evt);
            }
        });
        txtNombreTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTablaActionPerformed(evt);
            }
        });

        BtnNuevaTabla.setBackground(new java.awt.Color(193, 240, 249));
        BtnNuevaTabla.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnNuevaTabla.setForeground(new java.awt.Color(1, 22, 39));
        BtnNuevaTabla.setText("Nueva Tabla");
        BtnNuevaTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnNuevaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevaTablaActionPerformed(evt);
            }
        });

        BtnBorrarTabla.setBackground(new java.awt.Color(193, 240, 249));
        BtnBorrarTabla.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        BtnBorrarTabla.setForeground(new java.awt.Color(1, 22, 39));
        BtnBorrarTabla.setText("Borrar Tabla");
        BtnBorrarTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(1, 22, 39))); // NOI18N
        BtnBorrarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBusquedaSql)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BoxColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDatoBuscar)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnBuscarDato)
                                .addGap(18, 18, 18)
                                .addComponent(BtnBorrarDato)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCargarDatos))
                            .addComponent(BtnBuscarSql))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(boxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnNuevaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(boxEsquemas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNombreEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnNuevoEsquema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnBorrarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnBorrarEsquema, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxEsquemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNuevoEsquema)
                    .addComponent(BtnBorrarEsquema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNuevaTabla)
                    .addComponent(BtnBorrarTabla))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarDato)
                    .addComponent(BtnBorrarDato)
                    .addComponent(BtnCargarDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarSql))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEsquemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreEsquemaMouseClicked
        txtNombreEsquema.setText(" ");
    }//GEN-LAST:event_txtNombreEsquemaMouseClicked

    private void txtDatoBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDatoBuscarMouseClicked
        txtDatoBuscar.setText(null);
    }//GEN-LAST:event_txtDatoBuscarMouseClicked

    private void txtBusquedaSqlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBusquedaSqlMouseClicked
        txtBusquedaSql.setText(null);
    }//GEN-LAST:event_txtBusquedaSqlMouseClicked

    private void BtnNuevoEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoEsquemaActionPerformed
        if (!" ".equals(txtNombreEsquema.getText())) {
            agregarEsquema();

        } else {
            JOptionPane.showMessageDialog(this, "Por favor digite un nombre");
        }


    }//GEN-LAST:event_BtnNuevoEsquemaActionPerformed

    private void boxEsquemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEsquemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEsquemasActionPerformed

    private void BtnBorrarEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarEsquemaActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, "Seguro desea eliminar un esquema");
        if (JOptionPane.YES_OPTION == confirmacion) {
//            borrarEsquema();
            JOptionPane.showMessageDialog(this, " Se ha eliminado el esquema ");
        } else {
            JOptionPane.showMessageDialog(this, " No se ha elimnado nada ");
        }

    }//GEN-LAST:event_BtnBorrarEsquemaActionPerformed

    private void txtNombreTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreTablaMouseClicked
        txtNombreTabla.setText(" ");
    }//GEN-LAST:event_txtNombreTablaMouseClicked

    private void boxTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTablasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTablasActionPerformed

    private void txtNombreEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEsquemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEsquemaActionPerformed

    //DEBEMOS CONDICIONAR ESTE BOTON, DE TAL MANERA QUE SI EL BOX DE ESQUEMA ESTA VACIO NO PUEDE CREAR TABLAS //Listo
    // LUEGO CONDICIONAR LAS TABLAS SEGUN EL ESQUEMA SELECCIONADO //Esto no se como hacerlo????
    // DE MANERA SILIMAR LAS  COLUMNAS DE ACUERDO A LA TABLA DONDE SE CREARON

    private void BtnNuevaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevaTablaActionPerformed
        // InterfazNuevaTabla creacionJTable = new InterfazNuevaTabla();

        if (!txtNombreTabla.equals("") && !boxTablas.getSize().equals(null)) {
            agregarTabla();

        } else {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un nombre.");
        }

        //creacionJTable.setVisible(true); //FUNCIONANDO CORRECTAMENTE
    }//GEN-LAST:event_BtnNuevaTablaActionPerformed

    private void txtNombreTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTablaActionPerformed

    private void boxTablasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxTablasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTablasMouseClicked

    private void BtnBorrarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarTablaActionPerformed
        // borrarTabla();
    }//GEN-LAST:event_BtnBorrarTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxColumnas;
    private javax.swing.JButton BtnBorrarDato;
    private javax.swing.JButton BtnBorrarEsquema;
    private javax.swing.JButton BtnBorrarTabla;
    private javax.swing.JButton BtnBuscarDato;
    private javax.swing.JButton BtnBuscarSql;
    private javax.swing.JButton BtnCargarDatos;
    private javax.swing.JButton BtnNuevaTabla;
    private javax.swing.JButton BtnNuevoEsquema;
    private javax.swing.JComboBox<String> boxEsquemas;
    private javax.swing.JComboBox<String> boxTablas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrincipal;
    private javax.swing.JTextField txtBusquedaSql;
    private javax.swing.JTextField txtDatoBuscar;
    private javax.swing.JTextField txtNombreEsquema;
    private javax.swing.JTextField txtNombreTabla;
    // End of variables declaration//GEN-END:variables

    ArrayList<String> esquema;

    //Tablas tablaX;
    int cont = 1;
    int cont2 = 0;
    int contadorTablas = 0;

//    public void asignar_id() {
//
//        asignarId.put(cont, esquema.get(cont2));
//        cont++;
//        cont2++;
//        System.out.println(asignarId.size());
//    }
    public void agregarEsquema() {
        String name = txtNombreEsquema.getText();
        Esquema nuevo = new Esquema();
        nuevo.setNombre(name);
        nuevo.setEsquema_ID(SOMEBITS);
        controlador.agregarEsquema(nuevo);
        boxEsquemas.addItem(name);
        txtNombreEsquema.setText(" ");
        System.out.println(" Se ha guardado el esquema con exito ");

        for (int i = 0; i < esquema.size(); i++) {
            System.out.println(" NOMBRES DE ESQUEMAS CREADO " + esquema.get((i)));

        }

    }

//    public void borrarEsquema() {
//
//        esquema.remove(esquema.size() - 1);
//        boxEsquemas.removeItemAt(esquema.size());
//        asignarId.remove(cont);
//        System.out.println(asignarId.size() - 1 + " Tamaño del MAP ");
//        cont--;
//        cont2--;
//
//    }
   
    public void agregarTabla() {
        //InterfazNuevaTabla setNombre = new InterfazNuevaTabla();
        Tabla tabla = new Tabla();
        tabla.setNombre(txtNombreTabla.getText());
        Esquema esquema = controlador.getEsquemas().get(boxEsquemas.getSelectedIndex());
        esquema.getTablas().add(tabla);

        boxTablas.addItem(tabla.getNombre());
        txtNombreTabla.setText("");
        System.out.println("Se agrego una tabla correctamente");

    }

//    public void borrarTabla() {
//        tablas.remove(tablas.size() - 1);
//        boxTablas.removeItemAt(tablas.size());
//    }
    public void nameColumnas() {
        InterfazNuevaTabla obtenerNames = new InterfazNuevaTabla();

        BoxColumnas.addItem(obtenerNames.titulosColumnas.get(0));

    }

    //NO TOCAR!!!
//    public void crearColumnas(ArrayList<String> listaColumnas) {
//        //InterfazNuevaTabla obtenerTitulosColumnas = new InterfazNuevaTabla();
//        ArrayList<Tablas> tablas = new ArrayList<>();
//        this.tablas = tablas;
//
//        System.out.println(listaColumnas.size());
//        System.out.println(tablas.size());
    //System.out.println(obtenerTitulosColumnas.titulosColumnas.size());
    //int varTablas = tablas.indexOf(tablas.get(contadorTablas));
    //tablas.get(contadorTablas).setNumColumnas(listaColumnas.size());
    //System.out.println(tablas.get(contadorTablas).getNumColumnas());
    /*
        for (int i = 0; i < tablas.get(contadorTablas).getNumColumnas(); i++) {
            TableColumn tc = new TableColumn(i + 1, 80);
            jTablePrincipal.addColumn(tc);
        }
     */
//        contadorTablas++;
}

//}
